WIDTH=800
HEIGHT=600
FPS=60

WHITE=(255,255,255)
BLACK=(0,0,0)
RED=(255,0,0)
YELLOW=(255,255,0)


PLAYER_WIDTH=40
PLAYER_HEIGHT=40
PLAYER_START_HP=100
PLAYER_SPEED=6
PLAYER_SHOOT_COOLDOWN=20
PLAYER_SHOOT_TIMER=0
PLAYER_INVINCIBLE_TIMER=0

PLAYER_BULLET_SPEED=10

PLAYER_START_SHOOT_COOLDOWN = 20

PLAYER_DOUBLE_SHOT_ANGLE=15
PLAYER_TRIPLE_SHOT_ANGLE = 18

ENEMY_HP=1
ENEMY_WIDTH=30
ENEMY_HEIGHT=30
ENEMY_MIN_VX=-3
ENEMY_MAX_VX=3
ENEMY_MIN_VY=3
ENEMY_MAX_VY=3
ENEMY_SPAWN_RATE=0.01
ENEMY_SCORE=1

ENEMY_BULLET_SPEED=10
ENEMY_SHOOT_COOLDOWN=60
ENEMY_BULLET=5
ENEMY_SHOOT_PROBABILITY=0.02

BOSS_UNLOCK_SCORE = 60

BOSS_WIDTH = 120
BOSS_HEIGHT = 120
BOSS_HP = 50

BOSS_SPEED =8

BOSS_BULLET_SPEED = 6
BOSS_SHOOT_COOLDOWN = 50
BOSS_BULLET_DAMAGE = 5

BOSS_SPREAD_ANGLE = 15
BOSS_DOUBLE_SPREAD_ANGLE = 30



BACKGROUND_IMAGE_PATH = "assets/background.png"

PLAYER_IMAGE_PATH = "assets/player.png"
ENEMY_IMAGE_PATH = "assets/enemy.png"
BOSS_IMAGE_PATH = "assets/boss.png"

PLAYER_BULLET_IMAGE_PATH = "assets/player_bullet.png"
ENEMY_BULLET_IMAGE_PATH = "assets/enemy_bullet.png"
BOSS_BULLET_IMAGE_PATH = "assets/boss_bullet.png"

